const theme = {
  light: {
    mode: "light",
    bgColor: "#ffffff",
    txtColorPrimary: "#171619",
    btnColor: "#171619",
    btnTxtColor: "#ffffff",
    inputColor: "#f6f6f6",
    inputPlaceholder: "#bebec1",
    inputTxtColor: "#171619",
    linkedTxtColor: "#4d79dd",
    iconColor: "#707070",
    prevScreenIconColor: "#19181b",
    errorColor: "#eb746f",
    rulesColor: "#939393",
    googleBtnColor: "#de5d5b",
    facebookBtnColor: "#4893d3",
    disabledOnboardingColor: "#3d3b3a",
    disabledBtn: "#e1e1e1",
    disabledTxt: "#171717",
    paginatorColor: "#3d3b3a",
    switchTrackColor: "#eeeeee",
    switchIconColor: "#ffffff",
    switchThumbColor: "#f6c01a",
    disabledThumbColor: "#9499AD",
    disabledTrackColor: "#BCBFC9",
    disabledIconColor: "#eaeaea",
    otpInputColor: "#171619",
    statusBarColor: "default",
  },
  dark: {
    mode: "dark",
    bgColor: "#201e23",
    txtColorPrimary: "#eaeaea",
    btnColor: "#110f12",
    btnTxtColor: "#eaeaea",
    inputColor: "#110f12",
    inputPlaceholder: "#6f6f6f",
    inputTxtColor: "#eaeaea",
    linkedTxtColor: "#5c9dff",
    iconColor: "#eaeaea",
    prevScreenIconColor: "#eaeaea",
    errorColor: "#e84a43",
    rulesColor: "#6c6c6c",
    googleBtnColor: "#9b2c2b",
    facebookBtnColor: "#1b62a0",
    disabledOnboardingColor: "#eaeaea",
    disabledBtn: "#262529",
    disabledTxt: "#19191b",
    paginatorColor: "#bebebe",
    switchTrackColor: "#110f12",
    switchIconColor: "#eaeaea",
    switchThumbColor: "#0d4d86",
    disabledThumbColor: "#19191b",
    disabledTrackColor: "#262529",
    disabledIconColor: "#6c6c6c",
    otpInputColor: "#eaeaea",
    statusBarColor: "light-content",
  },
};

export default theme;
